# Generated by Django 4.2.21 on 2025-06-01 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('affiliation', models.CharField(choices=[('student', 'Kyoto University Student'), ('staff_researcher', 'Kyoto University Staff/Researcher'), ('other', 'Other')], default='student', max_length=20)),
                ('other_affiliation_details', models.CharField(blank=True, help_text="If 'Other' affiliation, please specify.", max_length=100, null=True)),
                ('self_assessed_level', models.CharField(choices=[('beginner', 'Beginner (N5 Equivalent)'), ('elementary', 'Elementary (N4 Equivalent)'), ('intermediate', 'Intermediate (N3 Equivalent)'), ('upper_intermediate', 'Upper-Intermediate (N2 Equivalent)'), ('advanced', 'Advanced (N1 Equivalent)'), ('unknown', 'Unsure / Need Assessment')], default='unknown', max_length=50, verbose_name='Self-Assessed Japanese Level')),
                ('preferred_class_level', models.CharField(choices=[('beginner', 'Beginner (N5 Equivalent)'), ('elementary', 'Elementary (N4 Equivalent)'), ('intermediate', 'Intermediate (N3 Equivalent)'), ('upper_intermediate', 'Upper-Intermediate (N2 Equivalent)'), ('advanced', 'Advanced (N1 Equivalent)'), ('unknown', 'Unsure / Need Assessment')], default='unknown', max_length=50, verbose_name='Preferred Class Level')),
                ('previous_experience', models.TextField(blank=True, null=True, verbose_name='Previous Japanese Learning Experience')),
                ('learning_goals', models.TextField(blank=True, null=True, verbose_name='What are your learning goals?')),
                ('questions_comments', models.TextField(blank=True, null=True, verbose_name='Any questions or comments?')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Sign-up Request',
                'verbose_name_plural': 'Sign-up Requests',
                'ordering': ['-timestamp'],
            },
        ),
    ]
